export const jobCategories = [
  { id: 'account-manager', name: 'Account Manager' },
  { id: 'accountant', name: 'Accountant' },
  { id: 'admin-assistant', name: 'Admin Assistant' },
  { id: 'animator', name: 'Animator' },
  { id: 'backend-developer', name: 'Backend Developer' },
  { id: 'blockchain-developer', name: 'Blockchain Developer' },
  { id: 'business-analyst', name: 'Business Analyst' },
  { id: 'content-writer', name: 'Content Writer' },
  { id: 'copywriter', name: 'Copywriter' },
  { id: 'data-scientist', name: 'Data Scientist' },
  { id: 'devops-engineer', name: 'DevOps Engineer' },
  { id: 'frontend-developer', name: 'Frontend Developer' },
  { id: 'fullstack-developer', name: 'Fullstack Developer' },
  { id: 'game-developer', name: 'Game Developer' },
  { id: 'graphic-designer', name: 'Graphic Designer' },
  { id: 'hr-manager', name: 'HR Manager' },
  { id: 'machine-learning-engineer ', name: 'Machine Learning Engineer' },
  { id: 'magazine-editor', name: 'Magazine Editor' },
  { id: 'marketing-manager', name: 'Marketing Manager' },
  { id: 'mobile-developer', name: 'Mobile Developer' },
  { id: 'operations-engineer', name: 'Operations Engineer' },
  { id: 'photographer', name: 'Photographer' },
  { id: 'product-designer', name: 'Product Designer' },
  { id: 'product-manager', name: 'Product Manager' },
  { id: 'qa-engineer', name: 'QA Engineer' },
  { id: 'recruiter', name: 'Recruiter' },
  { id: 'sales-manager', name: 'Sales Manager' },
  { id: 'scrum-master', name: 'Scrum Master' },
  { id: 'security-engineer', name: 'Security Engineer' },
  { id: 'seo-specialist', name: 'SEO Specialist' },
  { id: 'social-media-manager ', name: 'Social Media Manager' },
  { id: 'software-architect', name: 'Software Architect' },
  { id: 'software-engineer', name: 'Software Engineer' },
  { id: 'solution-architect', name: 'Solution Architect' },
  { id: 'technical-lead', name: 'Technical Lead' },
  { id: 'ui/ux-designer ', name: 'UI/UX Designer' },
  { id: 'ui/ux-engineer ', name: 'UI/UX Engineer' },
  { id: 'video-editor', name: 'Video Editor' },
  { id: 'web-developer', name: 'Web Developer' },
  { id: 'writer', name: 'Writer' },
];

export const jobLocationTypes = [
  { id: 'all', name: 'Any' },
  { id: 'remote', name: 'Remote' },
  { id: 'on-site', name: 'On-Site' },
  { id: 'hybrid', name: 'Hybrid' },
];

export const jobTypes = [
  { id: 'full-time', name: 'Full-Time' },
  { id: 'part-time', name: 'Part-Time' },
  { id: 'contract', name: 'Contract' },
  { id: 'temporary', name: 'Temporary' },
  { id: 'internship', name: 'Internship' },
  { id: 'freelance', name: 'Freelance' },
];

export const experienceLevelsOptions = [
  { id: 'entry-level', name: 'Entry Level' },
  { id: 'mid-level', name: 'Mid Level' },
  { id: 'senior-level', name: 'Senior Level' },
  { id: 'expert', name: 'Sensei Master' },
];
