export const PROVIDERS = {
  FIREBASE: 'firebase',
  SUPABASE: 'supabase',
};

export const POST_JOB_SELECTION_OPTIONS = {
  categories: [
    'Web Development',
    'Mobile Development',
    'Desktop Development',
    'Back-End Development',
    'Front-End Development',
    'DevOps',
    'QA and Testing',
    'Data Science',
    'Machine Learning',
    'AI and Natural Language Processing',
    'Other',
  ],
  skills: [
    'JavaScript',
    'HTML',
    'CSS',
    'React',
    'Angular',
    'Vue',
    'Node.js',
    'Express',
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'SQL Server',
    'Java',
    'C#',
    'Python',
    'PHP',
    'Ruby',
    'Go',
    'Django',
    'Flask',
    'Laravel',
    'Rails',
    'iOS',
    'Android',
    'Flutter',
    'Kotlin',
    'Swift',
    'Objective-C',
    'C++',
    'C',
    'Docker',
    'Kubernetes',
    'Ansible',
    'Terraform',
    'Jenkins',
    'Git',
    'Agile',
    'Scrum',
    'Jira',
    'TDD',
    'BDD',
    'Selenium',
    'Jest',
    'Mocha',
    'Chai',
    'PyTest',
    'RSpec',
    'NumPy',
    'Pandas',
    'Scikit-Learn',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'SpaCy',
    'NLTK',
    'Gensim',
    'Other',
  ],
};

export const ERROR_MESSAGES = {
  SAVE_JOB_ERROR_MESSAGE: 'You must be logged in to save jobs',
  SOMETHING_WENT_WRONG_MESSAGE: 'Something went wrong',
  JOB_SAVED_MESSAGE: 'Job saved!',
  JOB_REMOVED_MESSAGE: 'Job removed!',
};
